matrix:
  - name: Markdown
    expect_match: false
    aspell:
      lang: "de_DE"  # Deutsch statt 'en'
      dictionary:
        wordlists:
          - .wordlist.txt
        output: wordlist.dic
        encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
          ignores:
            - ':matches(code, pre)'
            - 'code'
            - 'pre'
            - 'blockquote'
    sources:
      - 'thevector/content/posts/2025/*.md'
      - '!thevector/content/*.md'
      - '!thevector/content/posts/about.md'

 
